### ISSUE TITLE
Admin features for team creation

### ISSUE THREAD

**Issue by mboutell** [Rosebotics/RoseboticsWeb#9]
To make it easier for Drs. Fisher and Boutell to create teams for their courses, we'd like an admin feature that lets you put in Rose usernames and forcefully enroll students in the team. Should work even before that student joins rosebotics.org.

**Comment by rockwotj** [comment]
How do we want to determine who an admin is? From the admin list built into AppEngine? Or should I add that to `config.py`?

**Comment by fisherds** [comment]
I'd like to just use the built in admin tool.  It's easy enough to add admins if needed.

The function users.is_current_user_admin() returns True if the current user is an administrator for the application.

https://cloud.google.com/appengine/docs/python/users/adminusers

btw Tyler I thought I added you as an admin once.  Did you leave the project or did I mis remember adding you?  I was pretty sure I gave you rights to do a push???

**Comment by rockwotj** [comment]
Naa, you gave me the password to Mechatronics student, who is the one who owns the project, and I pushed from that account. 

Was the password "Rose-Hulman"?

However it would make my development life easier if I had access from my gmail

**Comment by fisherds** [comment]
added rockwotj@gmail.com

you will need to accept the invitation, but you should be all set.

**Comment by fisherds** [comment]
Features remaining:
 - Using rose usernames
 - Allowing a CSV import of the class roster
 - Should work even before the student joins Rosebotics.org

**Comment by rockwotj** [comment]
I think right know you can do it for someone who is not a student. Rose username we had talked about..  That might revolve some big changes in the back end... I wish I could integrate this feature with Rosefire instead.

**Comment by rockwotj** [comment]
One better, can I just import from the course catalog?

**Comment by fisherds** [comment]
Yep.  I assume you mean the Schedule Lookup page???  The one that shows
the class roster.  That'd be fine with me.  I usually merge all of my
sections.  Really I'm just looking for a scalable way to always use the
Auto Sweep feature.  The current invitation model is too much trouble to
use and a really want to use the feature. :)

On Sat, Nov 28, 2015 at 12:27 AM, Tyler Rockwood <notifications@github.com>
wrote:

> One better, can I just import from the course catalog?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rosebotics/RoseboticsWeb/issues/9#issuecomment-160250409>
> .
>



-- 

Dr. Dave Fisher | Rose-Hulman |  fisherds@rose-hulman.com
<fisherds@rose-hulman.com> | 812-201-6488

**Comment by rockwotj** [comment]
Okay, I want to get my thoughts down on this one in a more definite way. 

You can create or edit a team by adding either gmail or rose emails. If you do it by rose emails then you do a look up by RHIT username field on the rosebotics student model. Grab the first student you find (this could allow phoney accounts... Since there is no verification or force of unique entries). Then use that rosebotics student to enroll. If no student is found, save them to a temporary table in the db. When a user's info is edited and a RHIT username is changed, then query this table for teams to add the user too. Delete anything if there is a match in the temp table.

As for bulk adding, I can do csv or grabbing from schedule look up based on term, and section. @fisherds do you have a preference? I'd rather only implement one of them.

**Comment by rockwotj** [comment]
CSV it is. I will pull from the email category.

**Comment by fisherds** [comment]
Things that are obvious, but I'll say them anyway.  Let's make sure the CSV import process is idempotent.  Also if 1 student joins let's make sure it's okay to just reimport an entire CSV again, which should ignore all the students that are already in and add only new people.  For removals, of course, can't be done via CSV.  The existing delete mechanism is already all set.

Fun stuff Tyler!
